# Generated by Django 4.2.3 on 2023-08-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
